name: crtweb-demo
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: 'npm:install'
        run: npm install
      - run: sudo apt update
      - name: test
        run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screens/